// <auto-generated />
using System;
using BnipiTask;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BnipiTask.Migrations
{
    [DbContext(typeof(BnipiTaskDbContext))]
    [Migration("20240526145827_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BnipiTask.Models.DesignObject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("DesignObjects");
                });

            modelBuilder.Entity("BnipiTask.Models.DocSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DesignObjectId")
                        .HasColumnType("char(36)");

                    b.Property<int>("MarkType")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DesignObjectId");

                    b.ToTable("DocSets");
                });

            modelBuilder.Entity("BnipiTask.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Cipher")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BnipiTask.Models.DesignObject", b =>
                {
                    b.HasOne("BnipiTask.Models.Project", "Project")
                        .WithMany("DesignObjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("BnipiTask.Models.DocSet", b =>
                {
                    b.HasOne("BnipiTask.Models.DesignObject", "DesignObject")
                        .WithMany("DocSets")
                        .HasForeignKey("DesignObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DesignObject");
                });

            modelBuilder.Entity("BnipiTask.Models.DesignObject", b =>
                {
                    b.Navigation("DocSets");
                });

            modelBuilder.Entity("BnipiTask.Models.Project", b =>
                {
                    b.Navigation("DesignObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
